---
- name: Define radvd configuration for prefix
  with_dict: "{{ tap_vpn_interfaces }}"
  notify: restart radvd
  blockinfile:
    dest: /etc/radvd.conf
    create: yes
    marker: "### {mark} IF {{ item.key }} ANSIBLE MANAGED BLOCK"
    block: |
      interface {{ item.key }} {
        AdvSendAdvert on;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        UnicastOnly on;
        prefix {{ item.value.ipv6 | ipsubnet(64) }} {
          AdvAutonomous on;
        };
      };
        
- name: Create configuration in /etc/interfaces.d/
  with_dict: "{{ tap_vpn_interfaces }}"
  notify: restart networking
  template: >
    src=interface.j2
    dest="/etc/network/interfaces.d/{{ item.key }}"
    owner=root
    group=root
    mode='0644'

- name: install dnsmasq, unbound, radvd, dibbler, openvpn (needed for persistant tap devices)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - unbound
  - dnsmasq
  - radvd
  - openvpn 
  - dibbler-server

- name: Create unbound interface configuration
  notify: restart unbound
  with_dict: " {{ tap_vpn_interfaces }}"
  template: >
    src=unbound.j2
    dest="/etc/unbound/unbound.conf.d/{{ item.key }}.conf"
    owner=root
    group=root
    mode='0644'

- name: Create dnsmasq interface configurations
  notify: restart dnsmasq
  with_dict: " {{ tap_vpn_interfaces }}"
  template: >
    src=dnsmasq.j2
    dest="/etc/dnsmasq.d/{{ item.key }}.conf"
    owner=root
    group=root
    mode='0644' 

- name: Create Dibbler Configuration
  notify: restart dibbler
  template: >
    src=server.conf.j2
    dest="/etc/dibbler/server.conf"
    owner=root
    group=root
    mode='0644'

- name: Create Prefix-Delegation Script for dibbler
  notify: restart dibbler
  template: >
    src=delegate.sh
    dest="/etc/dibbler/delegate.sh"
    owner=root
    group=root
    mode='0755'

- name: Bind dnsmasq to specified interfaces only
  notify: restart dnsmasq
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: bind-interfaces

- name: Disable dnsmasq's  DHCP service
  notify: restart dnsmasq
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: port=0
    regexp: ^port=

